### ISSUE TITLE
Upload , Store & View Documents

### ISSUE THREAD

**Issue by Gaukm01** [shoryak/hc_reimbursement#21]
This is a major part of our software and we need to update our code & fix the issue and add this function to store and view the uploaded documents from each profile as part of the View Form and View Transaction.

**Comment by sanchit-sinha** [comment]
Just a suggestion 
How about allowing users to upload documents in a folder on google drive and submit the shareable drive link !! 
 
This will allow them to update the document if needed as per their convenience, and also solve the issue of uploading multiple files or storing them in database.

**Comment by phoenix-23** [comment]
@sanchit-sinha your idea seems simple and do-able. The practical issue would be that the HC Admin would not have the document database stored for future reference (unlike the Forms) like they have now. Also, there can be some issues like the patient forgetting to give open access to those files/folder, etc.

**Comment by shoryak** [comment]
@sanchit-sinha @phoenix-23  Can't the HC download the documents when it is checking them , but still the access issue can create unnecessary problems. Alternative ideas any ?

**Comment by phoenix-23** [comment]
We can use the default `[FileField](https://docs.djangoproject.com/en/4.0/topics/http/file-uploads/)` in the form model.
And display them using the following code - 
`{% load static %}`
`<a href="{% static "user/uploads/{{ item.transaction.form.file }}" %}">my pdf</a>`

**Comment by shoryak** [comment]
> We can use the default [`FileField`](https://docs.djangoproject.com/en/4.0/topics/http/file-uploads/) in the form model. And display them using the following code - `{% load static %}` `<a href="{% static "user/uploads/{{ item.transaction.form.file }}" %}">my pdf</a>`

Did you try this ?

**Comment by sanchit-sinha** [comment]
> We can use the default [`FileField`](https://docs.djangoproject.com/en/4.0/topics/http/file-uploads/) in the form model. And display them using the following code - `{% load static %}` `<a href="{% static "user/uploads/{{ item.transaction.form.file }}" %}">my pdf</a>`

The number of files to upload will not be fixed imo. So we will have to create a seperate table for it and also will have to segregate images and PDFs. 

Or may be we also try saving zipped folders, but the only challenge then will be to display the files if we want it to be done..

**Comment by Gaukm01** [comment]
@sanchit-sinha  we can fix the number of flies to be uploaded to 1 as per our earlier idea of just having a single pdf uploaded containing all the documents.

**Comment by phoenix-23** [comment]
I agree with @Gaukm01. Adding a single `FileField` in the form model would allow one single file to be uploaded and that can be easily stored, accessed and displayed. Also if different file formats are not possible, we can restrict the format to pdf only.

**Comment by sanchit-sinha** [comment]
> I agree with @Gaukm01. Adding a single `FileField` in the form model would allow one single file to be uploaded and that can be easily stored, accessed and displayed. Also if different file formats are not possible, we can restrict the format to pdf only.

sounds good👍

**Comment by phoenix-23** [comment]
I have made a PR by applying the changes to incorporate 'FileFields'. Please have a look and if it is satisfactory, I think we can go ahead with it and close this issue and merge that PR.
