### ISSUE TITLE
Fixing formats for fields like contact number in Profile

### ISSUE THREAD

**Issue by shoryak** [shoryak/hc_reimbursement#23]
Currently, any length phone numbers are allowed in profile section , we can fix these minor issues

**Comment by shoryak** [comment]
One more related issue is to give a confirm password field in Frontend in signup page @atreya221 @Gaukm01 @phoenix-23 @sanchit-sinha

**Comment by Gaukm01** [comment]
We can also just add a CHANGE PASSWORD field in the Profile update part. @shoryak
