### ISSUE TITLE
Sign up page by hcadmin crashes is same email is used which already exists in database ( if all other fields above it are unique)

### ISSUE THREAD

**Issue by shoryak** [shoryak/hc_reimbursement#26]
Sign up page by hcadmin crashes is same email is used which already exists in database ( if all other fields above it are unique), its logic needs to be updated just like the other fields for username and roll.

**Comment by phoenix-23** [comment]
Yes, the same issue was solved for patient sign-up. Similar changes need to be done for the admin signup too.
