### ISSUE TITLE
Interface for adding medicine and tests in database for HCadmin

### ISSUE THREAD

**Issue by shoryak** [shoryak/hc_reimbursement#28]
Creating an interface for hcadmin to add tests and medicine to allow filling in form 
@phoenix-23 @Gaukm01  can you look into this ?/

**Comment by Gaukm01** [comment]
I will try to work on this today. @phoenix-23 maybe we can callaborate and complete this part. Just let me know of a time when you are free to work on this.

**Comment by sanchit-sinha** [comment]
@Gaukm01 Any update over the progress ?? 

I am building a page to display the available medicines and tests. Shall I take over this issue as well?

**Comment by Gaukm01** [comment]
@sanchit-sinha  Currently I have not started working on this issue yet. We can definitely collaborate and fix this issue.
