### ISSUE TITLE
Admin signup minor frontend issues 

### ISSUE THREAD

**Issue by shoryak** [shoryak/hc_reimbursement#33]
Rollnumber is asking for exactly 6 digits in admin signup for doctor/admin and message of getting account created is displayed in red in adminsignup.

**Comment by sanchit-sinha** [comment]
@shoryak roll number should be of exactly 6 digits, right ?

**Comment by shoryak** [comment]
> @shoryak roll number should be of exactly 6 digits, right ?

nope , that's exactly the problem, roll no should be of 6 to 12 digits in admin signup as institute ID of doctors etc will not necessarily be 6 digits , roll number for PGs etc ?

**Comment by sanchit-sinha** [comment]
> > @shoryak roll number should be of exactly 6 digits, right ?
> 
> nope , that's exactly the problem, roll no should be of 6 to 12 digits in admin signup as institute ID of doctors etc will not necessarily be 6 digits , roll number for PGs etc ? @sanchit-sinha

Yes, changes will need to be made in the db as well

**Comment by sanchit-sinha** [comment]
Will be dealt in the coming version !
