### ISSUE TITLE
The previous inputs remain on reloading page

### ISSUE THREAD

**Issue by Shrey0601** [shoryak/hc_reimbursement#44]
On the profile page, on reloading the page after updating the profile form, the information filled in the update form before realoding is not erased and same previous input is displayed.
![Screenshot (218)](https://user-images.githubusercontent.com/79155940/164886074-bd916ed5-d3df-4361-b01a-250e14b9b108.png)

**Comment by sanchit-sinha** [comment]
This seems to work fine by me..
https://www.loom.com/share/a2af7d465de24346a09bd8a3f8d7f743

Kindly clarify what exactly is the issue!

**Comment by Shrey0601** [comment]
Suppose I put something in the update profile fields and then reload the entire page then the inputs fed by me remain intact and I have to manually erase them on reloading the page if I want to update the fields fed by me earlier.

**Comment by shoryak** [comment]
> Suppose I put something in the update profile fields and then reload the entire page then the inputs fed by me remain intact and I have to manually erase them on reloading the page if I want to update the fields fed by me earlier.
@Shrey0601 

It can also be said that earlier autofill can help in making any further changes in updating the profile as it gives a template to fill in each field and thus might save time for the user , also in cases of making errors while updating the profile user can again update the profile quickly. So it doesn't seem to be a major issue, or it might be subjective for user to user.
