### ISSUE TITLE
Bug in updation of patient profile 

### ISSUE THREAD

**Issue by arnav4567** [shoryak/hc_reimbursement#45]
While updating the profile of a patient, if any field except "Contact" was updated, the page showed a warning prompt with the message "Please match the requested format", and the profile was not updated.

1. Go to the "Update Profile" section under the "Profile" tab.
2. Update any field except "Contact".
3. The warning prompt is seen.

![image](https://user-images.githubusercontent.com/75299021/164916165-c804ad4f-ed7e-4011-8940-8cb39f0dca2f.png)

Desktop specifications:
 - OS: Windows 11
 - Browser: Chrome

**Comment by phoenix-23** [comment]
All fields under the 'Update Profile' sections are 'text' fields except for the 'Contact' field. Hence they allow all kinds of input except for the Contact field which allows 10 digits only
